version: 2

sources:
  - name: raw
    description: Raw tables loaded by ingest (stats.nba.com API -> DuckDB)
    schema: raw
    tables:
      - name: team_game_logs
        description: One row per team per game from leaguegamelog (PlayerOrTeam=T)
      - name: player_game_logs
        description: One row per player per game from leaguegamelog (PlayerOrTeam=P)
      - name: team_rosters
        description: Team roster rows from commonteamroster endpoint
