version: 2

sources:
  - name: raw
    description: Raw tables loaded by load (stats.nba.com API -> DuckDB)
    schema: raw
    tables:
      - name: team_game_logs
        description: One row per team per game from leaguegamelog (PlayerOrTeam=T)
      - name: player_game_logs
        description: One row per player per game from leaguegamelog (PlayerOrTeam=P)
      - name: team_rosters
        description: Team roster rows from commonteamroster endpoint
      - name: common_all_players
        description: Master player list from commonallplayers (one row per player per season)
      - name: player_info
        description: Player bio (height, weight, school, draft) from commonplayerinfo
      - name: schedule
        description: Game schedule metadata (arena, tip time) from scoreboardv2 GameHeader
      - name: box_summaries
        description: Game summary (arena, officials, attendance) from boxscoresummaryv2 GameSummary
