# Run from project root so load and dbt use the same DB:
#   python -m load.load_warehouse --season 2026   # writes to warehouse.duckdb
#   DBT_PROFILES_DIR=transform dbt build --project-dir transform
# Path is relative to current working directory (project root).

nba_warehouse:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "warehouse.duckdb"
    prod:
      type: duckdb
      path: "warehouse.duckdb"
